name: makelint

on:
  - push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run linter
        # Run Linter
        run: |
          make lint
